import json
import os
from datetime import datetime
from typing import List, Dict, Any
from langchain_core.tools import tool
from db.firestore_client import get_firestore_client

# Helper to read fixtures
def _load_fixture(filename: str) -> dict:
    try:
        filepath = os.path.join(os.path.dirname(__file__), "..", "fixtures", filename)
        if os.path.exists(filepath):
            with open(filepath, "r", encoding="utf-8") as f:
                return json.load(f)
    except Exception as e:
        print(f"Error reading fixture {filename}: {e}")
    return {}

@tool
def generate_board_report_draft(
    report_type: str,            # "board" | "investor"
    period: str,                 # e.g. "Q2 2026" or "July 2026"
    user_id: str = "default_user"
) -> dict:
    """
    Generate draft official report for the Board of Directors or Investors.
    This report automatically consolidates current financial data, sales highlights,
    and strategic decisions retrieved from the database.
    
    Args:
        report_type: Report type, 'board' (formal, governance) or 'investor' (concise, growth metrics).
        period: Report period (e.g., 'Q2 2026' or 'July 2026').
        user_id: User ID.
        
    Returns:
        Dictionary containing report title, metadata, and full markdown content.
    """
    # 1. Fetch Finance Summary
    finance_data = _load_fixture("finance.json")
    curr_month = finance_data.get("current_month", {})
    cash_balance = curr_month.get("cash_balance", 750000000)
    monthly_revenue = curr_month.get("mrr", 180000000)
    runway = curr_month.get("cash_runway_months", 8.2)
    
    # 2. Fetch CRM highlights
    crm_data = _load_fixture("crm.json")
    open_deals = crm_data.get("sales_pipeline", {}).get("open_deals", 12)
    deals_value = crm_data.get("sales_pipeline", {}).get("pipeline_value", 450000000)
    customer_health = crm_data.get("customer_health", {})
    nps = customer_health.get("nps_score", 72)
    churn = customer_health.get("churn_rate_percent", 1.8)

    # 3. Fetch recent decisions from Firestore
    decisions_list = []
    try:
        db = get_firestore_client()
        docs = db.collection("decisions").where("userId", "==", user_id).limit(5).stream()
        for doc in docs:
            data = doc.to_dict()
            decisions_list.append(f"- **{data.get('title')}**: {data.get('decisionMade')} (Rationale: {data.get('rationale')})")
    except Exception as e:
        print("Error fetching decisions for report:", e)
        
    if not decisions_list:
        decisions_list = [
            "- *No new strategic decisions recorded*"
        ]
    decisions_text = "\n".join(decisions_list)
    
    # 4. Generate content based on report type
    title = f"{report_type.capitalize()} Performance Report - {period}"
    
    if report_type == "investor":
        markdown_content = f"""# {title}
**To**: Shareholders & Investors of Future Chief of Staff (CoS)
**Date**: {datetime.utcnow().strftime('%B %d, %Y')}
**Period**: {period}

---

## 1. Executive Summary
The business operated with solid performance during the period {period}. Our primary focus remains on market expansion and customer retention optimization. The current cash runway is at a safe level, supporting sustainable growth.

## 2. Key Financial Metrics (Financial Health)
*   **Monthly Revenue (MRR)**: IDR {monthly_revenue:,.0f}
*   **Cash & Cash Equivalents Balance**: IDR {cash_balance:,.0f}
*   **Cash Runway**: {runway} Months

## 3. Growth & Sales Metrics (CRM)
*   **Active Sales Pipeline**: {open_deals} Deals (Total Value: IDR {deals_value:,.0f})
*   **Net Promoter Score (NPS)**: {nps}
*   **Monthly Churn Rate**: {churn}%

## 4. Strategic Decisions & Use of Funds
{decisions_text}

---
*Automatically generated by Future Chief of Staff (CoS) Assistant.*
"""
    else:
        # Board of Directors Report
        markdown_content = f"""# {title}
**To**: Board of Directors & Commissioners
**Date**: {datetime.utcnow().strftime('%B %d, %Y')}
**Period**: {period}
**Classification**: Confidential / Internal Only

---

## I. Financial & Governance Overview
Governance report on the company's financial performance and capital allocation plans.
*   **Total Cash Available**: IDR {cash_balance:,.0f}
*   **Cash Health**: Cash runway of {runway} months provides adequate operational flexibility.
*   **Monthly Operating Revenue**: IDR {monthly_revenue:,.0f}

## II. Operations & Customer Relationship Management (CRM)
*   **Pipeline Activity**: Sales show a strong outlook with {open_deals} open deals valued at IDR {deals_value:,.0f}.
*   **Customer Satisfaction**: NPS remains high at {nps}, with a target of keeping monthly churn below 2% (currently {churn}%).

## III. Board Governance Decision Log
The following are the key strategic decisions taken that require Board oversight:
{decisions_text}

## IV. Action Plan (Next Steps)
1. Maintain runway stability by controlling the monthly burn rate.
2. Accelerate the sales pipeline closing cycle.
3. Optimize onboarding of new key staff.

---
*This report is presented for the evaluation of the Board of Directors.*
"""

    return {
        "title": title,
        "report_type": report_type,
        "period": period,
        "content_markdown": markdown_content.strip(),
        "generated_at": datetime.utcnow().isoformat() + "Z"
    }

@tool
def render_report_card(
    title: str,
    report_type: str,
    period: str,
    content_markdown: str
) -> str:
    """
    Display the draft Board/Investor report visually on the user's chat screen (Generative UI).
    Call this tool after you call 'generate_board_report_draft' to present the report preview to the user.
    
    Args:
        title: Report title.
        report_type: Report type ('board' or 'investor').
        period: Report period (e.g. 'Q2 2026').
        content_markdown: Full report content in Markdown.
    """
    return "Displaying Report Draft..."
